config/routes.rb
Rails.application.routes.draw do
  # get "categories/new"
  # get "categories/show"
  # get "categories/index"
  root "pages#home"

  devise_for :admins
  resources :posts, :categories, :comments
  resources :admins, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :admin
  has_and_belongs_to_many :categories
  has_many :comments, dependent: :destroy

  def word_count
    self.body.split.size
  end

  def reading_time
    (word_count / 180.0).ceil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :show_categories, :show_latest_post, :comments

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def show_categories
    @categories = Category.all
  end

  def show_latest_post
    @latest_post = Post.last
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :destroy]

  def new
    @category = Category.new
  end

  def create
    category = Category.create(category_params)
    redirect_to categories_path
  end

  def show
    @category = Category.find_by(id: params[:id])
  end

  def index
    @categories = Category.all
  end

  def destroy
    category = Category.find_by(id: params[:id])
    category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:comment][:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :comment))
    redirect_to post_path(@post)
  end

  def destroy
    comment = Comment.find(params[:id])
    post = comment.post_id
    comment.destroy
    redirect_to post_path(post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def new
    @post = Post.new
  end

  def update
    post = Post.find_by(id: params[:id])
    post.update(post_params)
    redirect_to post_path
  end

  def create
    post = current_admin.posts.create(post_params)
    redirect_to posts_path
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def destroy
    post = Post.find_by(id: params[:id])
    post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = [:hard_wrap, :autolink, :no_intraemphasis]
    Markdown.new(text, *options).to_html.html_safe
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f|%>
<div>
<%= f.label :name %>
<%= f.text_field :name, required: true%>
</div>

<%= f.submit %>
<% end %>

app/views/categories/_index.html.erb
<h2>All Categories</h2>
<% @categories.each do |category|%>
<div><%= category.name%></div><span><%= link_to("Delete  ", category_path(category), method: :delete) %> 
<% end%>

app/views/categories/_show.html.erb
<% @category.posts.each do |post|%>
<%= post.title%>
 <p><%= raw markdown(post.body).truncate(300)%><%= link_to "Read more", post_path(post)%></p>
<% end %>

app/views/categories/index.html.erb
<h2>All Categories</h2>
<% if admin_signed_in? %>
  <%= render partial: "index"%>
  <% end%>
<% @categories.each do |category|%>
<div><%= category.name%></div><span>

<% end%>

app/views/categories/new.html.erb
<h2>New Category</h2>
<%= render partial: "form"%>

app/views/categories/show.html.erb
<% @category.posts.each do                                                                                           |post|%>
<%= post.title%>
 <p><%= raw markdown(post.body).truncate(300)%><%= link_to "Read more", post_path(post)%></p>
<% end %>

app/views/comments/_comment.html.erb
    <li class="comment ">
       <div class="comment"> 
        </a> <div class="info">
      <img class="comment" src="https://webiconspng.com/wp-content/uploads/2016/11/account_avatar_human_male_man_people_person_profile_user_users_icon_325966-300x300.png" alt="Profile Avatar" title="Anie Silverston" />

            <span class="user-comment"><%= comment.name %></span><span class="comment-time">    4 hours ago</span>
        </div>
        <div><p class="comment"><%= comment.comment %></p></div>
        
         <%= link_to 'Delete', comment_path(comment),
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %></div>
      
    </li>  
    
   
    
  

app/views/comments/_comment2.html.erb
<ul class="comment-section">

    <li class="comment user-comment">
       
       <a class="avatar" href="#">
            <img src="https://webiconspng.com/wp-content/uploads/2016/11/account_avatar_human_male_man_people_person_profile_user_users_icon_325966-300x300.png" width="35" alt="Profile Avatar" title="Anie Silverston" />
        </a> <div class="info">
            <a href="#">Anie Silverston</a>
            <span>4 hours ago</span>
        </div>
        
        <p>Suspendisse gravida sem?</p>
    </li>

    <li class="comment author-comment">
        <div class="info">
            <a href="#">Jack Smith</a>
            <span>3 hours ago</span>
        </div>
        <a class="avatar" href="#">
            <img src="https://webiconspng.com/wp-content/uploads/2016/11/account_avatar_human_male_man_people_person_profile_user_users_icon_325966-300x300.png" width="35" alt="Profile Avatar" title="Jack Smith" />
        </a>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse gravida sem sit amet molestie portitor.</p>

    </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>أفق</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Aref+Ruqaa:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display+SC|Montserrat:300" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script
  src="http://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
 

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
  <nav>
<ul>
<li>
<div class="cloud">
 
  <%=link_to(image_tag("https://avatanplus.com/files/resources/mid/598759701a4ed15db8b55dec.png", width: 100, height: 100), root_path, class: "cloud-nav")%>

  <h5 class="center"><strong>أُفُق</strong></h5>
</div>
</li>
  
  <li> <%= link_to "All Posts", posts_path, :class => "text"%>
</li>
<% if admin_signed_in? %>
    
           


  <li> <%= link_to "New Post", new_post_path , :class => "text"%></li>
  <li>      <%= link_to "Log Out", destroy_admin_session_path, method: :delete, :class => "text"	%></li>
<% end%>
</ul>


</nav>
  <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/pages/_show.html.erb
<!--
<% category.posts.each do |post|%>
<div><img class="home_categories" src="<%= post.image %>" alt="">
<h4 ><%= post.title%></h4>
 <p><%= raw markdown(post.body).truncate(300)%><%= link_to "Read more", post_path(post)%></p></div>

<% end %>
-->

<div class="row tab-cat center-align">
 <% category.posts.each do |post|%>

<div class="cat-col"> <div class="col s1 ">
      <div class="card small">
        <div class="card-image">
          <img class="materialboxed" src="<%= post.image %>">
          <span class="card-title"><%= post.title%></span>
        </div>
        <div class="card-content">
          <p><%= raw markdown(post.body).truncate(300)%></p>
        </div>
        <div class="card-action">
          <%= link_to "Read more", post_path(post), class:"cyan-text text-accent-4"%>
        </div>
      </div>
    </div>
 </div>
   
<% end %>
 </div>

app/views/pages/home.html.erb
 <h2>Latest Post</h2>
 <div class="row latest center-align">
    <div class="col s12 m7 center-align">
      <div class="card">
        <div class="card-image">
          <img  src="<%= show_latest_post.image %>">
          <span class="card-title"><%= show_latest_post.title%></span>
        </div>
        <div class="card-content">
          <p><%= raw markdown(show_latest_post.body).truncate(300)%></p>
        </div>
        <div class="card-action">
          <%= link_to "Read more", post_path(show_latest_post), class:"cyan-text text-accent-4"%>
        </div>
      </div>
    </div>
  </div>
     <div class="row tab ">
    <div class="col s12">
      <ul class="tabs ">
      <% i=1%>
       <% show_categories.each do |category|%>

        <li class="tab col s3 cyan-text text-accent-4"><a class="active cyan-text text-accent-4" href="#test<%=i%>"><%= category.name%></a></li>
        
       <% i+=1%>
        <% end%>
      </ul>
    </div>
    <%j=1%>
    <% show_categories.each do |category|%>
    <div id="test<%=j%>" class="col s12"><%= link_to render(:partial => 'show', locals: {category: category}), category_path(category.id), class: "home_categories"%></div>
     
    <% j +=1%>
   
    <%end%>
  </div>      
 

 </div>
 

        
       

app/views/pages/home2.html.erb
<h1>This is home 2</h1>

app/views/posts/_admin_index.html.erb
<p>Great to see you around, <%= current_admin.name %>!</p>
<span><%= link_to "Log Out", destroy_admin_session_path, method: :delete	%> </span>
    <h2>All Posts</h2>
    <span><%= link_to("New Post ", new_post_path) %> </span>
   <!--<% @posts.each do |post|%>
    <div class= "category"> <%post.categories.each do |post_category|%>
<span class= "category"><%= post_category.name%></span>
<% end %></div>
   <img class="post" src="<%= post.image%>" alt="">
    <h3><%= post.title%></h3>
      </span> <span><%= link_to("Delete Post ", post_path(post), method: :delete) %>     </span> </span></div>
    <p><%= post.body.truncate(300)%><%= link_to "Read more", post_path(post)%></p>
    <% end%>--> 
     
     <% @posts.each do |post|%>
   <div class="row latest space center-align">
    <div class="col s12 m7 center-align">
      <div class="card">
        <div class="card-image">
          <img  src="<%= post.image%>">
          <span class="card-title"><%= post.title%></span>
           <span><%= link_to("Delete Post ", post_path(post), method: :delete) %>     </span> 
        </div>
        <div class="card-content">
          <p><%=  raw markdown(post.body).truncate(300)%></p>
        </div>
        <div class="card-action">
          <%= link_to "Read more", post_path(post), class:"cyan-text text-accent-4"%>
        </div>
        
      </div>
    </div>
  </div>
  <% end %>

app/views/posts/_admin_show.html.erb
<div><%= link_to("  Edit Post ", edit_post_path(@post)) %></div> 
<div class="post"><article><%=raw  markdown(@post.body) %></article></div>
<section class="section comments">
    <div class="container">
        <span class="comment"><strong><%= @post.comments.count %> Comments</strong> </span>
        <%= render @post.comments %>
        <div class="comment-form">
            <hr />
             <span class="comment"><strong>Leave a reply</strong></span>
             <%= render partial: 'comment' %>
        </div>
    </div>
</section>

app/views/posts/_comment.html.erb
<%= form_for @post.comments.new do |f|%>
    <%= hidden_field_tag "comment[post_id]", params[:id]%>
<div>
<%= f.label :name %>
<%= f.text_field :name, required: true%>
<%= f.label :comment %>
<%= f.text_field :comment, required: true%>
</div>

<%= f.submit %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post ,html: {:class => 'x'} do |f|%>
<div>

<%= f.label :title %>
<%= f.text_field :title, required: true%>
</div>
<%= f.label :image %>
<%= f.text_area :image, required: true%>
<div><%= f.label :category_ids, "choose categories:" %></div>
<p>
<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
<%#= f.collection_check_boxes(:category_ids, Category.all, :id, :name) { |b| b.label(text: "Test") { b.check_box} } %>
</p>
  </div>
  <%= link_to "add category", new_category_path	%>
<div>
<div><%= f.label :body %></div>

<%= f.text_area :body, required: true%>

</div>
<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render partial: "form"%>

app/views/posts/index.html.erb
<% if admin_signed_in? %>
    <%= render partial: "admin_index"%>
<% else %>

    <h2>All Posts</h2>
    <!--  <% @posts.each do |post|%>
 <div> <%post.categories.each do |post_category|%>
<span class= "category"><%= post_category.name%></span>
<% end %></div>
 <img class="post" src="<%= post.image%>" alt="">
    <h3><%= post.title%></h3>
    <p><%=  raw markdown(post.body).truncate(100)%><%= link_to "Read more", post_path(post)%></p>
   <span> <%=post.comments.count %> comments</span>
    <% end%> -->
  
<% @posts.each do |post|%>
<div class="row latest center-align">
    <div class="col s12 m7 center-align">
      <div class="card">
        <div class="card-image">
          <img  src="<%= post.image%>">
          <span class="card-title"><%= post.title%></span>
        </div>
        <div class="card-content">
          <p><%=  raw markdown(post.body).truncate(300)%></p>
        </div>
        <div class="card-action">
          <%= link_to "Read more", post_path(post), class:"cyan-text text-accent-4"%>
        </div>
        
      </div>
    </div>
  </div>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<h2>New Post</h2>
<%= render partial: "form"%>

app/views/posts/show.html.erb
<div class="article" >
<div class="image-title"><img class="post"src="<%= @post.image%>" alt="">
<h1 class="bottom-left"><%=@post.title%></h1></div>
<div><% if @post.admin %>
<span class="post-info">by:  <%= link_to @post.admin.name %></span>
<% else %>
<span class="post-info">written by: anynomus</span>
<% end%><span class="post-info">Posted <%= time_ago_in_words @post.created_at%> ago</span>
<span class="post-info"><%= @post.reading_time%> min read</span>
 </div>


<% if admin_signed_in? %>
    <%= render partial: "admin_show"%>
   
<% else %>


<div class="post"><article><%=  raw markdown(@post.body) %></article></div>

    
        <span class="comment"><strong><%= @post.comments.count %></strong> Comments</span>
      <!--<%= render partial: "comments/comment2"%> -->
     <div class="box">
     <ul class="comment-section">
     <%= render @post.comments %>
     </ul></div> 
       
        <div class="comment-form">
            <span class="comment">Leave a reply</span>
             <%= render partial: 'comment' %>
        </div>
    

<% end%>




</div>